version: '3'

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      # exclude volumes below
      - /app/.git
    ports:
      - ${PORT:-8080}:8080
    tty: true
    stdin_open: true

volumes:
  node_modules:
